CREATE DATABASE grabber default CHARACTER SET UTF8;
use grabber;
CREATE TABLE info(
    userip VARCHAR(300) PRIMARY KEY NOT NULL,
    useragent VARCHAR(300),
    currentdate DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;
